<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.donnypz.mccore</groupId>
    <artifactId>core</artifactId>
    <version>3.0.0</version>
    <packaging>pom</packaging>

    <name>MCCore</name>
    <modules>
        <module>api</module>
        <module>loader</module>
        <module>v1_21_1</module>
        <module>v1_21_3</module>
        <module>v1_21_4</module>
        <module>v1_21_5</module>
        <module>v1_21_6</module>
        <module>v1_21_8</module>
    </modules>

    <properties>
        <mccore.version>3.0.0</mccore.version>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.donnypz.mccore</groupId>
                <artifactId>api</artifactId>
                <version>${mccore.version}</version>
            </dependency>

            <dependency>
                <groupId>net.donnypz.mccore</groupId>
                <artifactId>loader</artifactId>
                <version>${mccore.version}</version>
            </dependency>

            <dependency>
                <groupId>net.donnypz.mccore</groupId>
                <artifactId>v1_21_1</artifactId>
                <version>${mccore.version}</version>
            </dependency>

            <dependency>
                <groupId>net.donnypz.mccore</groupId>
                <artifactId>v1_21_3</artifactId>
                <version>${mccore.version}</version>
            </dependency>

            <dependency>
                <groupId>net.donnypz.mccore</groupId>
                <artifactId>v1_21_4</artifactId>
                <version>${mccore.version}</version>
            </dependency>

            <dependency>
                <groupId>net.donnypz.mccore</groupId>
                <artifactId>v1_21_5</artifactId>
                <version>${mccore.version}</version>
            </dependency>

            <dependency>
                <groupId>net.donnypz.mccore</groupId>
                <artifactId>v1_21_6</artifactId>
                <version>${mccore.version}</version>
            </dependency>

            <dependency>
                <groupId>net.donnypz.mccore</groupId>
                <artifactId>v1_21_8</artifactId>
                <version>${mccore.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>sk89q-repo</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>
        <repository>
            <id>enginehub-maven</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>

    <!--FlowNBT-->
        <repository>
            <id>rapture-releases</id>
            <url>https://repo.rapture.pw/repository/maven-releases/</url>
        </repository>
        <repository>
            <id>rapture-snapshots</id>
            <url>https://repo.rapture.pw/repository/maven-snapshots/</url>
        </repository>
    <!--FlowNBT-->


        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>

        <!-- InfernalSuite RELEASE -->
        <repository>
            <id>is-releases</id>
            <url>https://repo.infernalsuite.com/repository/maven-releases/</url>
        </repository>

        <!-- InfernalSuite SNAPSHOT -->
        <repository>
            <id>is-snapshots</id>
            <url>https://repo.infernalsuite.com/repository/maven-snapshots/</url>
        </repository>


        <!--NoteBlockAPI-->
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>

        <!--ASP-->


        <!--<dependency>
            <groupId>com.flowpowered</groupId>
            <artifactId>flow-nbt</artifactId>
            <version>2.0.2</version>
            <scope>provided</scope>
        </dependency>-->
        <!--ASP-->

        <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-bukkit</artifactId>
            <version>7.3.5</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.sk89q.worldguard</groupId>
            <artifactId>worldguard-bukkit</artifactId>
            <version>7.0.10</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.github.koca2000</groupId>
            <artifactId>NoteBlockAPI</artifactId>
            <version>1.6.2</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
