name: MCCore
version: '${project.version}'
main: net.donnypz.mccore.Core
api-version: 1.20
softdepend: [LuckPerms, WorldGuard, NoteBlockAPI, ProtocolLib]
loadbefore: [DisplayEntityUtils]
commands:
  corereload:
    permission: "core.reload"
    description:
    usage:
  gmc:
    description:
    usage:
    aliases: [gm1, creative]
  gms:
    description:
    usage:
    aliases: [gm0, survival]
  gma:
    description:
    usage:
    aliases: [gm2, adventure]
  gmsp:
    description:
    usage:
    aliases: [gm3, spectator]
  fly:
    description:
    usage:
  cc:
    description:
    usage:
  ci:
    description:
    usage:
  day:
    description:
    usage:
  noon:
    description:
    usage:
  night:
    description:
    usage:
  midnight:
    description:
    usage:
  speed:
    description:
    usage:
  previewborder:
    description:
    usage:
  centerplayer:
    description:
    usage: